#!/usr/bin/env python3

import os
import sys
from optparse import OptionParser

parser = OptionParser()
parser.add_option("--start", action="store_true", dest="on", default=True, help="Start Hornet Systemd Service. (default)")
parser.add_option("--stop", action="store_false", dest="on", help="Stop Hornet Systemd Service.")

(options, args) = parser.parse_args()

if os.geteuid() != 0:
    print("You need root permissions to do this!")
    sys.exit(1)

if options.on:
    print("Starting Hornet Systemd Service.")
    os.system('systemctl start hornet')
else:
    print("Stopping Hornet Systemd Service.")
    os.system('systemctl stop hornet')
